# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
